### ISSUE TITLE
		How to solve the problem of make erro

### ISSUE THREAD

**Issue by liuchenchn** [MIDA-group/itkAlphaAMD#1]
when I run  ~/download/itkAlphaAMD-build$ make		
The following error occurred,do you know how to solve it?
My version is cmake-3.11.3 and InsightToolkit-4.9.0;

/home/lc/download/itkAlphaAMD/source/common/itkImageProcessingTools.h: In static member function ‘static ValueType itk::IPT<ValueType, Dim>::HannFunc(ValueType)’:
/home/lc/download/itkAlphaAMD/source/common/itkImageProcessingTools.h:686:33: error: ‘twopi’ is not a member of ‘itk::Math’
         return 0.5 * (1.0 - cos(itk::Math::twopi * tt));
                                 ^
CMakeFiles/TestMCDS.dir/build.make:62: recipe for target 'CMakeFiles/TestMCDS.dir/testMCDS.cpp.o' failed
make[2]: *** [CMakeFiles/TestMCDS.dir/testMCDS.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TestMCDS.dir/all' failed
make[1]: *** [CMakeFiles/TestMCDS.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tristaaan** [comment]
I have this working with itk 4.9.13 on MacOS. 
I'm not using HEAD, I think the readme has not been updated for the recent changes so I'm on da320c5.
